### ISSUE TITLE
Use keyword arguments when initializing operators

### ISSUE THREAD

**Issue by apocolistm** [panovvv/airflow-livy-plugins#10]
https://github.com/panovvv/airflow-livy-operators/blob/master/airflow_home/plugins/airflow_livy/session.py#L271
https://github.com/panovvv/airflow-livy-operators/blob/master/airflow_home/plugins/airflow_livy/session.py#L290
https://github.com/panovvv/airflow-livy-operators/blob/master/airflow_home/plugins/airflow_livy/session.py#L291
make it key-value pls, otherwise it occures error in 2.1.2 airflow version

**Comment by panovvv** [comment]
Roger that! :)
