### ISSUE TITLE
LivySessionOperator uses "queue" param reserved by baseoperator

### ISSUE THREAD

**Issue by apocolistm** [panovvv/airflow-livy-plugins#6]
Please rename this param, otherwise it put task in wrong queue for airflow workers

**Comment by panovvv** [comment]
Well spotted, thanks!
Fixed that in the newest release (0.4.0), please verify and feel free to close the issue if it works for you now.

**Comment by apocolistm** [comment]
Work like a charm! thanks for quick response.
